import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { Providers } from "./GlobalRedux/provider";
import { Inter } from "next/font/google";
import { ThirdWebProviderWrapper } from "./ThirdWeb/thirdwebprovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Spaces Marketplace",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} cz-shortcut-listen={"true"}>
        <ThirdWebProviderWrapper>
          <Providers>
            <Navbar />
            {children}
          </Providers>
        </ThirdWebProviderWrapper>
      </body>
    </html>
  );
}
